### ISSUE TITLE
Bug: pageLoaded "and" (isVisible, inDom) condition: ignored

### ISSUE THREAD

**Issue by firepol** [qualityshepherd/protractor-example#5]
Hi, I'm new to protractor & selenium and I'm having difficulties to understand how your example work for the pageLoaded part.

I'd expect that the page is loaded and if there is e.g. a condition e.g. for the githubPage `this.pageLoaded = this.isVisible(this.username);` then the test will fail is the username text is not visible in the page, but it doesn't.

E.g. I tried to change to `this.pageLoaded = this.isVisible('whatever_text_you_want');`

But the test doesn't fail. Same also in the nonAngularLoginPage:
```
    this.pageLoaded = this.and(
        this.isVisible($('#a_non_existing_id'))
    );
```

Again I run the tests and no error.

What I expected: if I set a selector, for pageLoaded to throw an error if the element I specified in the selector is not visible... please check also the other methods in the basePage e.g. inDom etc. or let me know how I'm supposed to understand this.

I'm testing inside WebStorm (debug/run protractor).

At the moment all tests are green except 1 failing: _should add a new friend_ (but this fails for another reason, not because of the pageLoaded).

Cheers ;)

**Comment by qualityshepherd** [comment]
Thanks for this! I'd forgotten to fix this in my example code. Fixed in commit 6046ed0
